@startuml
title Leaderboard

autoactivate on

actor Player

Player -> Leaderboard : getLeaderboardEntries()

Leaderboard -> GameService : getGameRecords(COMPUTER)
return GameRecord[]

Leaderboard --> Player: LeaderboardEntry[]
@enduml
