@startuml

title Log in

actor Player
participant LoginForm
collections Players

Player -> LoginForm ** 

loop user has no token
    loop form fields incomplete
        Player -> LoginForm: fillUserDetails(username, password)
        activate LoginForm
            LoginForm -> LoginForm : validateFields()
            activate LoginForm
            LoginForm --> LoginForm : validation_errors
            deactivate LoginForm

            alt validation_errors.length > 0
                LoginForm --> Player : displayErrors(validation_errors)
            end
        deactivate LoginForm
    end

    Player -> LoginForm : submit(loginForm)
    activate LoginForm
    LoginForm -> Players : getPlayerByUsernamePassword(username, password)
    activate Players

    alt no user found
        Players --> LoginForm : null
        LoginForm --> Player : displayError("invalid user credentials")
    else
        Players --> LoginForm : player
        deactivate Players
        LoginForm --> Player : token
        deactivate LoginForm
    end
end

@enduml

