@startuml

title Offer Draw


actor Player1
actor Player2

note right
Player1 is assumed to start the draw negotiation
end note

Player1 -> Game : offerDraw()
activate Game
Game -> Player2 : getDrawResponse()
activate Player2
alt Player2 accepts draw
    Player2 --> Game:  True
break
    Game -> Game : draw()
activate Game
    Game -> GameRecord: saveGame(self)

deactivate Game
end
    Game --> Player1 : True
else
    Player2 --> Game : False
    deactivate Player2
    Game --> Player1 : False
deactivate Game
end

@enduml

