@startuml Play Against Computer

title Play Against Computer

autoactivate on

actor HumanPlayer
actor RLAgent
HumanPlayer -> Game: createGame(self, False)
return Game
HumanPlayer -> Game: assignPlayer(self, Side color)
    Game -> Game: startGame()
        Game -> Board: initializeBoard()
        return Board
    deactivate
    return True

loop game has not ended
        
    alt HumanPlayer's turn
        break player decides to concede
            HumanPlayer -> Game: concede()
            Game -> GameRecord: saveGame(self)
            deactivate
            deactivate
        end
        Game -> HumanPlayer: getMove(board)
        return string
    else AI's turn
        Game -> RLAgent: getMove(board)
        return string
    end
    autoactivate off
    Game -> Board: updateBoard(move)
        activate Board
            Board -> Board: validateMove(move)
                activate Board
                deactivate Board
            Board -> Board: isRepetition(move)
                activate Board
                deactivate Board
            Board -> Board: isCheckmate(move)
                activate Board
                deactivate Board
            Board -> Board: isStalemate(move)
                activate Board
                deactivate Board
            alt move is invalid
                Board --> Game : false
            else move is valid
                Board -> Move : storeMove()
                Board --> Game : true
                deactivate Board
            end
    autoactivate on
end

Game -> GameRecord: saveGame(self)
deactivate

@enduml
