@startuml Play Against Computer

title Play Against Computer

autoactivate on

actor HumanPlayer
actor RLAgent
HumanPlayer -> Game: Game(False)
return Game
HumanPlayer -> Game: assignPlayer(self, Side color)
    Game -> Game: startGame()
        Game -> Board: initializeBoard()
        return Board
    return True
    deactivate

loop game has not ended
        
    alt HumanPlayer's turn
        break player decides to concede
            HumanPlayer -> Game: concede()
            Game -> GameRecord: saveGame(self)
            deactivate
            deactivate
        end
        Game -> HumanPlayer: getMove(board)
        return string
    else AI's turn
        Game -> RLAgent: getMove(board)
        return string
    end
    Game -> Board: updateBoard(move)
        activate Board
            Board -> Board: validateMove(move)
            deactivate
            Board -> Board: isRepetition(move)
            deactivate
            Board -> Board: isCheckmate(move)
            deactivate
            Board -> Board: isStalemate(move)
            deactivate
            alt move is invalid
                Board --> Game : false
            else move is valid
                Board -> Move : storeMove()
                deactivate
                Board --> Game : true
            end
        deactivate Board
end

Game -> GameRecord: saveGame(self)
deactivate

@enduml
