@startuml

actor BlackPlayer
actor WhitePlayer

loop game not finished
    loop move played is invalid
        alt black turn
            Game -> BlackPlayer : getMove(board)
            activate BlackPlayer
            BlackPlayer --> Game : move
            deactivate BlackPlayer
        else white turn
            Game -> WhitePlayer : getMove(board)
            activate WhitePlayer
            WhitePlayer --> Game : move
            deactivate WhitePlayer
        end
        Game -> Board : move(move)
        activate Board
            Board -> Board : validateMove(move)
            activate Board
                Board -> Board : isRepetition(move)
                    activate Board
                    deactivate Board
                Board -> Board : isCheckmate(move)
                    activate Board
                    deactivate Board
                Board -> Board : isStalemate(move)
                    activate Board
                    deactivate Board
            deactivate Board

            alt move is invalid
                Board --> Game : false
            else move is valid
                Board -> Board : updateBoard(move)
                Board -> Move : storeMove()
                Board --> Game : true
                deactivate Board
            end
        deactivate Board
    end

    Game -> Game : turn++
end

Game -> GameRecord ** : GameRecord(game)
@enduml
