@startuml

title Registration

actor User
participant RegistrationForm
participant Player
collections Players

User -> RegistrationForm **

loop user not created
    loop form fields incomplete
        User -> RegistrationForm: fillUserDetails(username, password)
        activate RegistrationForm
            RegistrationForm -> RegistrationForm : validateFields()
            activate RegistrationForm
            return validation_errors
        alt validation_errors.length > 0
            return displayFieldErrors()
        end
    end
    User -> RegistrationForm : submit(registrationForm)
    activate RegistrationForm

    RegistrationForm -> Players : getPlayerByUsername(username)
    activate Players

    alt user exists
        Players --> RegistrationForm : player
        RegistrationForm --> User : displayError("user already exists")
    else
        Players --> RegistrationForm: null
        deactivate Players
        RegistrationForm -> Player **
        RegistrationForm -> Player : save()
        activate Player
        deactivate Player
    end
end

RegistrationForm -> LoginForm **
RegistrationForm --> User : loginForm
deactivate RegistrationForm

@enduml

