@startuml

title Start a PvP game

actor Host
actor Player

Host -> Game : createGame(host, pvp=True)
activate Game
Game --> Host : Game
deactivate Game

alt Player has not logged in
   ref over Player, Game: login
end
Player -> Game : addPlayer(player)
activate Game
deactivate Game

    Host -> Game : assignPlayer(host, color=color)
    Game -> Game : assignPlayer(player, color=other_color)
    activate Game
    Game -> Game : startGame()
    activate Game
Game -> Board : initializeBoard()
activate Board
Board --> Game : Board
deactivate Board
    deactivate Game

Game --> Host: True
deactivate Game

ref over Host, Player, Game, Board : Play PvP

@enduml
